name: SonarCloud Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better analysis
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        cd frontend && npm install
        cd ../backend && npm install
        
    - name: Run backend tests with coverage
      run: |
        cd backend
        npm run test:coverage || true  # Don't fail if tests fail - we want to see coverage
        
    - name: Run frontend tests with coverage  
      run: |
        cd frontend
        npm test -- --coverage --watchAll=false || true  # Don't fail if tests fail
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate at sonarcloud.io
        
    - name: Upload coverage reports (optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: |
          frontend/coverage/
          backend/coverage/
